language: java
jdk:
  - openjdk11

# Travis CI를 어느 브랜치가 푸시될 때 수행하는지 지정.
# master 브랜치만
branches:
  only:
    - main

# Travis CI 서버의 Home
# gradle을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐싱하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build" # master branch가 푸시되었을 때 수행하는 명령어

# deploy 명령어가 실행되기 전
before_deploy:
 - zip -r spring-todo * # CodeDeploy는 jar 파일을 인식하지 못하므로 jar 파일과 기타 설정 파일들을 .zip으로 압축
 - mkdir -p deploy
 - mv spring-todo.zip deploy/spring-todo.zip # 생성된 zip 파일을 deploy 폴더로 이동

# S3로 파일 업로드 혹은 CodeDeploy로 배포 등 외부 서비스와 연동될 행위들을 선언
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: spring-todo-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # 앞서 생성한 deploy 폴더의 파일들만 S3로 전달
    wait-until-deploy: true

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - hwankim1941@gmail.com