version: 0.0 # CodeDeploy의 버전. 프로젝트 버전이 아니므로 0.0외에 다른 버전을 사용하면 오류 발생
os: linux
files:
    # CodeDeploy에서 전달해준 파일 중 destination으로 옮길 파일 지정. 루트 경로로 지정할 경우 전체 파일을 옮김
  - source: /
    # source에서 지정된 파일을 받을 위치. 이후 Jar을 실행하는 등은 destination에 옮겨진 파일들로 진행
    destination: /home/ec2-user/spring-todo/repo/zip
    overwrite: yes # 기존에 파일들이 있으면 덮어쓸지를 결정.