version: 0.0 # CodeDeploy의 버전. 프로젝트 버전이 아니므로 0.0외에 다른 버전을 사용하면 오류 발생
os: linux
files:
    # CodeDeploy에서 전달해준 파일 중 destination으로 옮길 파일 지정. 루트 경로로 지정할 경우 전체 파일을 옮김
  - source: /
    # source에서 지정된 파일을 받을 위치. 이후 Jar을 실행하는 등은 destination에 옮겨진 파일들로 진행
    destination: /home/ec2-user/spring-todo/repo/zip
    overwrite: yes # 기존에 파일들이 있으면 덮어쓸지를 결정.

# CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 설정
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# hooks : CodeDeploy 배포단계에서 실행할 명령어를 지정
hooks:
  AfterInstall:
    - location: stop.sh # 엔진엑스와 연결되어있지 않은 스프링 부트를 종료
      timeout: 60
      runas: ec2-user
  ApplicationStart: # ApplicationStart 명령 실행 단계에서 아래 명령어들을 실행
    - location: start.sh # 엔진엑스와 연결되어있지 않은 Port로 새 버전의 스프링 부트를 실행
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새 스프링 부트가 정상적으로 실행됐는지 확인
      timeout: 60
      runas: ec2-user