language: java
jdk:
  - openjdk11

# Travis CI를 어느 브랜치가 푸시될 때 수행하는지 지정.
# master 브랜치만
branches:
  only:
    - master

# Travis CI 서버의 Home
# gradle을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐싱하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build" # master branch가 푸시되었을 때 수행하는 명령어

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - hwankim1941@gmail.com